export enum LanguageCode {
  Chinese = 'zh',
  Catalan = 'ca',
  Danish = 'da',
  Dutch = 'nl',
  English = 'en',
  French = 'fr',
  German = 'de',
  Greek = 'el',
  Italian = 'it',
  Japanese = 'ja',
  Lithuanian = 'lt',
  Macedonain = 'mk',
  MultiLanguage = 'xx',
  NorweiganBokmål = 'nb',
  Polish = 'pl',
  Portuguese = 'pt',
  Romanian = 'ro',
  Russian = 'ru',
  Spanish = 'es',
}
